<?xml version="1.0" encoding="utf-8"?><Database Name="SieuThiDB" Class="SieuThiDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TIC8QEU\SQLEXPRESS;Initial Catalog=SieuThiDB;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="SieuThiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoaiLH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="MoTaKhac" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ManvNext" Method="ManvNext">
    <Parameter Name="manv" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>