<?xml version="1.0" encoding="utf-8"?><Database Name="DataQLST" Class="SieuThiDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=K3MSHIRO\SQLEXPRESS;Initial Catalog=DataQLST;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="DataQLSTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoaiLH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="MoTaKhac" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="NhanVien_DonHang" Member="DonHangs" ThisKey="MaNV" OtherKey="MaNV" Type="DonHang" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.GianHang" Member="GianHangs">
    <Type Name="GianHang">
      <Column Name="MaGianHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGianHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiHangMa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiHang_GianHang" Member="LoaiHang" ThisKey="LoaiHangMa" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="MaSoThue" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="NhaCungCap_Hang" Member="Hangs" ThisKey="MaNCC" OtherKey="MaNCC" Type="Hang" />
    </Type>
  </Table>
  <Table Name="dbo.Hang" Member="Hangs">
    <Type Name="Hang">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MaLoaiHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Hang_HangBan" Member="HangBans" ThisKey="MaHang" OtherKey="MaHang" Type="HangBan" />
      <Association Name="Hang_HangNhap" Member="HangNhaps" ThisKey="MaHang" OtherKey="MaHang" Type="HangNhap" />
      <Association Name="NhaCungCap_Hang" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="LoaiHang_Hang" Member="LoaiHang" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHang" Member="LoaiHangs">
    <Type Name="LoaiHang">
      <Column Name="MaLoaiHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiHang_GianHang" Member="GianHangs" ThisKey="MaLoaiHang" OtherKey="LoaiHangMa" Type="GianHang" />
      <Association Name="LoaiHang_Hang" Member="Hangs" ThisKey="MaLoaiHang" OtherKey="MaLoaiHang" Type="Hang" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayDH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_HangNhap" Member="HangNhaps" ThisKey="MaDH" OtherKey="MaDH" Type="HangNhap" />
      <Association Name="NhanVien_DonHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangBan" Member="HangBans">
    <Type Name="HangBan">
      <Column Name="SoHD" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Hang_HangBan" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
      <Association Name="HoaDon_HangBan" Member="HoaDon" ThisKey="SoHD" OtherKey="SoHoaDon" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangNhap" Member="HangNhaps">
    <Type Name="HangNhap">
      <Column Name="MaDH" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DonHang_HangNhap" Member="DonHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonHang" IsForeignKey="true" />
      <Association Name="Hang_HangNhap" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="SoHoaDon" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_HangBan" Member="HangBans" ThisKey="SoHoaDon" OtherKey="SoHD" Type="HangBan" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DSHB" Member="DSHBs">
    <Type Name="DSHB">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoanhThu" Member="DoanhThus">
    <Type Name="DoanhThu">
      <Column Name="ngayThongKe" Type="System.DateTime" DbType="SmallDateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doanhThuHomNay" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="tienLaiHomNay" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="maHangBanChay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soLuongBanChay" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangBanTrongThang" Member="HangBanTrongThangs">
    <Type Name="HangBanTrongThang">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>

  <Function Name="dbo.ManvNext" Method="ManvNext">
    <Parameter Name="manv" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GianHangNext" Method="GianHangNext">
    <Parameter Name="MaGianHang" Parameter="maGianHang" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LoaiHangGanNhat" Method="LoaiHangGanNhat">
    <Parameter Name="MaLoaiHang" Parameter="maLoaiHang" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MaNhaCCNext" Method="MaNhaCCNext">
    <Parameter Name="MaNCC" Parameter="maNCC" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.tinhTongDoanhThuThang" Method="tinhTongDoanhThuThang">
    <Parameter Name="NgayThang" Parameter="ngayThang" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <ElementType Name="tinhTongDoanhThuThangResult">
      <Column Name="" Member="Column1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>